Test results

diff --git a/.github/workflows/aiter-test.yaml b/.github/workflows/aiter-test.yaml
--- a/.github/workflows/aiter-test.yaml
+++ b/.github/workflows/aiter-test.yaml
@@ -242,6 +242,38 @@ jobs:
         run: |
           docker rm -f aiter_test || true
 
+  standard-test-results:
+    if: always()
+    name: Standard Test Results
+    runs-on: ubuntu-latest
+    needs: [standard]
+    steps:
+      - name: Download all test logs
+        uses: actions/download-artifact@v4
+        with:
+          name: standard-test-log-*-shard-*-logs
+      
+      - name: Check Standard Test Results
+        run: |
+          set -ex
+          echo "Checking Standard Test Results..."
+          all_passed=true
+          for shard in {0..4}; do
+            for runner in {linux-aiter-mi355-1,aiter-1gpu-runner}; do
+              if [ ! -f standard-test-log-${runner}-shard-${shard}-logs ]; then
+                echo "Test report for shard ${shard} not found."
+                all_passed=false
+                break
+              fi
+            done
+          done
+          if [ "$all_passed" = true ]; then
+            echo "All tests passed."
+          else
+            echo "Test failures or errors detected."
+            exit 1
+          fi
+
   multi-gpu:
     name: Multi-GPU Tests (8 GPU)
     if: github.ref == 'refs/heads/main'
diff --git a/.github/workflows/triton-test.yaml b/.github/workflows/triton-test.yaml
--- a/.github/workflows/triton-test.yaml
+++ b/.github/workflows/triton-test.yaml
@@ -185,7 +185,7 @@ jobs:
 
       - name: Upload test logs
         uses: actions/upload-artifact@v4
-        if: always()
+        if: success()
         with:
           name: triton-test-shard-${{ matrix.shard }}-logs
           path: test-reports/triton.xml
@@ -194,3 +194,33 @@ jobs:
         if: always()
         run: |
           docker rm -f triton_test || true
+
+  triton-test-results:
+    if: always()
+    name: Triton Test Results
+    runs-on: ubuntu-latest
+    needs: [triton]
+    steps:
+      - name: Download all test reports
+        uses: actions/download-artifact@v4
+        with:
+          name: triton-test-shard-*-logs
+      
+      - name: Check Triton Test Results
+        run: |
+          set -ex
+          echo "Checking Triton Test Results..."
+          all_passed=true
+          for shard in {0..7}; do
+            if [ ! -f triton-test-shard-${shard}-logs ]; then
+              echo "Test report for shard ${shard} not found."
+              all_passed=false
+              break
+            fi
+          done
+          if [ "$all_passed" = true ]; then
+            echo "All tests passed."
+          else
+            echo "Test failures or errors detected."
+            exit 1
+          fi
